
package Telas;

import Beans.UsuariosDTO;
import Telas.Cadastro.CadClientesView;
import Telas.Cadastro.CadLivrosView;
import Telas.Cadastro.CadUsuariosView;
import Telas.Cadastro.CadVendasView;

/**
 * tela de menu
 *
 * @javadoc
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        lblNivel.setText(UsuariosDTO.getUsuarios());
        if (UsuariosDTO.getUsuarios().equalsIgnoreCase("Operador")) {
            jbnUsuarios.setVisible(false);
            jbnUsuarios.setEnabled(false);
        }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbnLivros = new javax.swing.JButton();
        jbnClientes = new javax.swing.JButton();
        jbnUsuarios = new javax.swing.JButton();
        jbnSair = new javax.swing.JButton();
        jbnVendas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(205, 154, 103));

        jbnLivros.setBackground(new java.awt.Color(0, 0, 0));
        jbnLivros.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jbnLivros.setForeground(new java.awt.Color(255, 215, 0));
        jbnLivros.setText("Livros");
        jbnLivros.setBorder(null);
        jbnLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnLivrosActionPerformed(evt);
            }
        });

        jbnClientes.setBackground(new java.awt.Color(0, 0, 0));
        jbnClientes.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jbnClientes.setForeground(new java.awt.Color(255, 215, 0));
        jbnClientes.setText("Clientes");
        jbnClientes.setBorder(null);
        jbnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnClientesActionPerformed(evt);
            }
        });

        jbnUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        jbnUsuarios.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jbnUsuarios.setForeground(new java.awt.Color(255, 215, 0));
        jbnUsuarios.setText("Usuarios");
        jbnUsuarios.setBorder(null);
        jbnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnUsuariosActionPerformed(evt);
            }
        });

        jbnSair.setBackground(new java.awt.Color(0, 0, 0));
        jbnSair.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jbnSair.setForeground(new java.awt.Color(255, 215, 0));
        jbnSair.setText("sair");
        jbnSair.setBorder(null);
        jbnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnSairActionPerformed(evt);
            }
        });

        jbnVendas.setBackground(new java.awt.Color(0, 0, 0));
        jbnVendas.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jbnVendas.setForeground(new java.awt.Color(255, 215, 0));
        jbnVendas.setText("Vendas");
        jbnVendas.setBorder(null);
        jbnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnVendasActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(196, 136, 76));
        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nivel de acesso:");

        lblNivel.setForeground(new java.awt.Color(0, 0, 0));
        lblNivel.setText("Overwatch");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbnVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbnLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNivel)))
                        .addGap(0, 183, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jbnLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbnVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbnLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnLivrosActionPerformed
        CadLivrosView cl = new CadLivrosView();
        cl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbnLivrosActionPerformed

    private void jbnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnClientesActionPerformed
        CadClientesView cc = new CadClientesView();
        cc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbnClientesActionPerformed

    private void jbnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnVendasActionPerformed
        CadVendasView cv = new CadVendasView();
        cv.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jbnVendasActionPerformed

    private void jbnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnUsuariosActionPerformed
        CadUsuariosView cu = new CadUsuariosView();
        cu.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jbnUsuariosActionPerformed

    private void jbnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnSairActionPerformed
        LoginView lv = new LoginView();
        lv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbnClientes;
    private javax.swing.JButton jbnLivros;
    private javax.swing.JButton jbnSair;
    private javax.swing.JButton jbnUsuarios;
    private javax.swing.JButton jbnVendas;
    private javax.swing.JLabel lblNivel;
    // End of variables declaration//GEN-END:variables
}
